# Generated by Django 4.2.6 on 2023-11-08 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_pedido_productos_pedido_activo_detallepedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='productos',
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='productos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_pedido', to='home.producto'),
        ),
    ]
