# Generated by Django 4.2.6 on 2023-11-08 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_detallepedido_productos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='productos',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_pedido_productos', to='home.producto'),
        ),
    ]
