# Generated by Django 4.2.6 on 2024-04-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_detallepedido_productos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallepedido',
            options={'verbose_name': 'DetallePedido', 'verbose_name_plural': 'DetallePedidos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
